version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 1
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/qrcode"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 1
