"""Add google calendar event mapping table

Revision ID: 27312971d87f
Revises: ccd8d535c4a2
Create Date: 2025-10-12 03:55:45.988409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27312971d87f'
down_revision: Union[str, None] = 'ccd8d535c4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_event_mapping',
    sa.Column('event_id', sa.BINARY(length=16), nullable=False, comment='Event ID'),
    sa.Column('google_calendar_id', mysql.VARCHAR(length=255), nullable=False, comment='Google Calendar ID'),
    sa.Column('google_event_id', mysql.VARCHAR(length=255), nullable=False, comment='Google Event ID'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_calendar_event_mapping')),
    info={'shard_ids': {'shard0', 'shard1'}},
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_google_calendar_event_mapping_user_id'), 'google_calendar_event_mapping', ['user_id', 'event_id'], unique=False)
    op.drop_column('google_calendar_integration', 'last_error')
    op.drop_column('google_calendar_integration', 'last_sync_at')
    # ### end Alembic commands ###


def downgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_integration', sa.Column('last_sync_at', mysql.DATETIME(), nullable=True, comment='Last Sync Time'))
    op.add_column('google_calendar_integration', sa.Column('last_error', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='Last Error Message'))
    op.drop_index(op.f('ix_google_calendar_event_mapping_user_id'), table_name='google_calendar_event_mapping')
    op.drop_table('google_calendar_event_mapping')
    # ### end Alembic commands ###


def upgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_event_mapping',
    sa.Column('event_id', sa.BINARY(length=16), nullable=False, comment='Event ID'),
    sa.Column('google_calendar_id', mysql.VARCHAR(length=255), nullable=False, comment='Google Calendar ID'),
    sa.Column('google_event_id', mysql.VARCHAR(length=255), nullable=False, comment='Google Event ID'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_calendar_event_mapping')),
    info={'shard_ids': {'shard0', 'shard1'}},
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_google_calendar_event_mapping_user_id'), 'google_calendar_event_mapping', ['user_id', 'event_id'], unique=False)
    op.drop_column('google_calendar_integration', 'last_error')
    op.drop_column('google_calendar_integration', 'last_sync_at')
    # ### end Alembic commands ###


def downgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_integration', sa.Column('last_sync_at', mysql.DATETIME(), nullable=True, comment='Last Sync Time'))
    op.add_column('google_calendar_integration', sa.Column('last_error', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='Last Error Message'))
    op.drop_index(op.f('ix_google_calendar_event_mapping_user_id'), table_name='google_calendar_event_mapping')
    op.drop_table('google_calendar_event_mapping')
    # ### end Alembic commands ###

