"""Rename Event start/end columns to dtstart/dtend for RFC 5545 compliance

Revision ID: 51eeefefc423
Revises: c5beee9cc314
Create Date: 2025-08-09 15:56:03.868272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51eeefefc423'
down_revision: Union[str, None] = 'c5beee9cc314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename start column to dtstart
    op.alter_column('event', 'start',
               new_column_name='dtstart',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='DTSTART')
    
    # Rename end column to dtend
    op.alter_column('event', 'end',
               new_column_name='dtend',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='DTEND')
    # ### end Alembic commands ###


def downgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename dtstart column back to start
    op.alter_column('event', 'dtstart',
               new_column_name='start',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='Start')
    
    # Rename dtend column back to end
    op.alter_column('event', 'dtend',
               new_column_name='end',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='End')
    # ### end Alembic commands ###


def upgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename start column to dtstart
    op.alter_column('event', 'start',
               new_column_name='dtstart',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='DTSTART')
    
    # Rename end column to dtend
    op.alter_column('event', 'end',
               new_column_name='dtend',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='DTEND')
    # ### end Alembic commands ###


def downgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename dtstart column back to start
    op.alter_column('event', 'dtstart',
               new_column_name='start',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='Start')
    
    # Rename dtend column back to end
    op.alter_column('event', 'dtend',
               new_column_name='end',
               existing_type=mysql.DATETIME(timezone=True),
               nullable=False,
               comment='End')
    # ### end Alembic commands ###

