"""add event goal and review tables

Revision ID: 8b437fd296a3
Revises: 1dcdc4592a9e
Create Date: 2025-11-21 12:32:43.573996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b437fd296a3'
down_revision: Union[str, None] = '1dcdc4592a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_goal',
    sa.Column('event_id', sa.BINARY(length=16), nullable=False, comment='Event ID'),
    sa.Column('start', mysql.DATETIME(timezone=True), nullable=False, comment='Event Start Time'),
    sa.Column('goal_text', mysql.TEXT(), nullable=False, comment='Goal Description'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_goal')),
    sa.UniqueConstraint('user_id', 'event_id', 'start', name=op.f('uq_event_goal_user_id')),
    info={'shard_ids': {'shard1', 'shard0'}},
    mysql_engine='InnoDB'
    )
    op.create_table('event_review',
    sa.Column('event_id', sa.BINARY(length=16), nullable=False, comment='Event ID'),
    sa.Column('start', mysql.DATETIME(timezone=True), nullable=False, comment='Event Start Time'),
    sa.Column('review_text', mysql.TEXT(), nullable=False, comment='Review Description'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_review')),
    sa.UniqueConstraint('user_id', 'event_id', 'start', name=op.f('uq_event_review_user_id')),
    info={'shard_ids': {'shard1', 'shard0'}},
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_review')
    op.drop_table('event_goal')
    # ### end Alembic commands ###


def upgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_goal',
    sa.Column('event_id', sa.BINARY(length=16), nullable=False, comment='Event ID'),
    sa.Column('start', mysql.DATETIME(timezone=True), nullable=False, comment='Event Start Time'),
    sa.Column('goal_text', mysql.TEXT(), nullable=False, comment='Goal Description'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_goal')),
    sa.UniqueConstraint('user_id', 'event_id', 'start', name=op.f('uq_event_goal_user_id')),
    info={'shard_ids': {'shard1', 'shard0'}},
    mysql_engine='InnoDB'
    )
    op.create_table('event_review',
    sa.Column('event_id', sa.BINARY(length=16), nullable=False, comment='Event ID'),
    sa.Column('start', mysql.DATETIME(timezone=True), nullable=False, comment='Event Start Time'),
    sa.Column('review_text', mysql.TEXT(), nullable=False, comment='Review Description'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_review')),
    sa.UniqueConstraint('user_id', 'event_id', 'start', name=op.f('uq_event_review_user_id')),
    info={'shard_ids': {'shard1', 'shard0'}},
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_review')
    op.drop_table('event_goal')
    # ### end Alembic commands ###

