"""Make recurrence_rule.wkst nullable for RFC 5545 compliance

Revision ID: c5beee9cc314
Revises: 6424cf329e2d
Create Date: 2025-08-09 15:00:25.809998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5beee9cc314'
down_revision: Union[str, None] = '6424cf329e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurrence_rule', 'wkst',
               existing_type=mysql.ENUM('MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU', collation='utf8mb4_general_ci'),
               nullable=True,
               existing_comment='WKST')
    # ### end Alembic commands ###


def downgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurrence_rule', 'wkst',
               existing_type=mysql.ENUM('MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU', collation='utf8mb4_general_ci'),
               nullable=False,
               existing_comment='WKST')
    # ### end Alembic commands ###


def upgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurrence_rule', 'wkst',
               existing_type=mysql.ENUM('MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU', collation='utf8mb4_general_ci'),
               nullable=True,
               existing_comment='WKST')
    # ### end Alembic commands ###


def downgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurrence_rule', 'wkst',
               existing_type=mysql.ENUM('MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU', collation='utf8mb4_general_ci'),
               nullable=False,
               existing_comment='WKST')
    # ### end Alembic commands ###

