"""Add google calendar integration table

Revision ID: ccd8d535c4a2
Revises: 306828e98a27
Create Date: 2025-09-20 17:15:09.836607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccd8d535c4a2'
down_revision: Union[str, None] = '306828e98a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_integration',
    sa.Column('google_user_id', mysql.VARCHAR(length=255), nullable=False, comment='Google User ID'),
    sa.Column('google_email', mysql.VARCHAR(length=255), nullable=False, comment='Google Email'),
    sa.Column('encrypted_access_token', mysql.TEXT(), nullable=False, comment='Encrypted Access Token'),
    sa.Column('encrypted_refresh_token', mysql.TEXT(), nullable=False, comment='Encrypted Refresh Token'),
    sa.Column('token_expires_at', mysql.DATETIME(timezone=True), nullable=False, comment='Token Expiry'),
    sa.Column('calendar_id', mysql.VARCHAR(length=255), nullable=False, comment='Google Calendar ID'),
    sa.Column('calendar_url', mysql.VARCHAR(length=512), nullable=False, comment='Public Calendar URL'),
    sa.Column('sync_status', mysql.ENUM('DISCONNECTED', 'CONNECTED', 'SYNCING', 'ERROR'), nullable=False, comment='Sync Status'),
    sa.Column('last_sync_at', mysql.DATETIME(timezone=True), nullable=True, comment='Last Sync Time'),
    sa.Column('last_error', mysql.TEXT(), nullable=True, comment='Last Error Message'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_calendar_integration')),
    sa.UniqueConstraint('google_user_id'),
    info={'shard_ids': {'shard0', 'shard1'}},
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_calendar_integration')
    # ### end Alembic commands ###


def upgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_integration',
    sa.Column('google_user_id', mysql.VARCHAR(length=255), nullable=False, comment='Google User ID'),
    sa.Column('google_email', mysql.VARCHAR(length=255), nullable=False, comment='Google Email'),
    sa.Column('encrypted_access_token', mysql.TEXT(), nullable=False, comment='Encrypted Access Token'),
    sa.Column('encrypted_refresh_token', mysql.TEXT(), nullable=False, comment='Encrypted Refresh Token'),
    sa.Column('token_expires_at', mysql.DATETIME(timezone=True), nullable=False, comment='Token Expiry'),
    sa.Column('calendar_id', mysql.VARCHAR(length=255), nullable=False, comment='Google Calendar ID'),
    sa.Column('calendar_url', mysql.VARCHAR(length=512), nullable=False, comment='Public Calendar URL'),
    sa.Column('sync_status', mysql.ENUM('DISCONNECTED', 'CONNECTED', 'SYNCING', 'ERROR'), nullable=False, comment='Sync Status'),
    sa.Column('last_sync_at', mysql.DATETIME(timezone=True), nullable=True, comment='Last Sync Time'),
    sa.Column('last_error', mysql.TEXT(), nullable=True, comment='Last Error Message'),
    sa.Column('id', sa.BINARY(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_calendar_integration')),
    sa.UniqueConstraint('google_user_id'),
    info={'shard_ids': {'shard0', 'shard1'}},
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_calendar_integration')
    # ### end Alembic commands ###

